### ISSUE TITLE
Zone cleaning

### ISSUE THREAD

**Issue by mikkelsiggaard** [BenjaminPaap/home-assistant-myneato#10]
Thank you for doing this work - it's awesome! 

On my D9 I can't seem to get "Zone cleaning" from HA working. 
I am testing use a HA Script, seen below. 

> vacuum.ursulaservice: myneato.custom_cleaning
data:
  mode: eco
  zone: Living Room
target:
  entity_id: vacuum.ursula`

And I have defined "Living Room" as an area to be cleaned in the Neato app. 

Am I doing something wrong, is this not supported or is it a bug? 
From this comment it seems like I'm doing something wrong? 
https://github.com/BenjaminPaap/home-assistant-myneato/issues/2#issuecomment-1340634998

I'm not much of a developer myself, but I'll be happy to test stuff.

**Comment by BenjaminPaap** [comment]
Should be working. I don't have any problems advising my robot to only clean a specific room. Please ensure, that there are no spaces at the beginning or end of your room name in the neato app. This tap Action of a card works for me:


  tap_action:
        action: call-service
        service: myneato.custom_cleaning
        data:
          mode: max
          zone: Wohnzimmer
        target:
          entity_id: vacuum.roberta

**Comment by mikkelsiggaard** [comment]
Your tap action works perfectly for me, even though I don't see why my original solution won't work. 

But thanks a lot!
