### ISSUE TITLE
Entities?

### ISSUE THREAD

**Issue by dlasher** [BenjaminPaap/home-assistant-myneato#2]
First, thank you for working on this, nice to see *some* support for the D8/D9/D10's.

Second, I have a D10, was able to add it just fine, however, I'm only seeing (1) entity, and that's the battery level. Shouldn't see a bit more than that, like schedules, camera/map, etc? and have options to trigger/stop cleaning? (current status?)

**Comment by vandenbogerd** [comment]
I had the same question. Added the D10 today.

**Comment by BenjaminPaap** [comment]
Currently there is only the battery level and the vacuum itself supported. Schedules are already on my todo list, but time is limited. Maps are a bit different. I think I got the data, but I have no Idea how to get an image from that data. Data doesn't look familiar to me. If you can help here I would love to see a PR.

**Comment by vandenbogerd** [comment]
After a few hours, the vacuum appeared. So for now all is good. 

If you need any help: just let me know. I’m glad to help out (with a D10).

**Comment by BenjaminPaap** [comment]
@dlasher can I close this one or do you need any further assistance?

**Comment by vandenbogerd** [comment]
For me it can be closed. I don’t know about @dlasher

**Comment by dlasher** [comment]
I had the same experience -- gave it some time, and entities appeared. I added them to my dashboard and now I can stop/start/view the status.

Looking forward to being able to trigger a clean to a specific zone, etc, but this is a great start, thank you!

**Comment by BenjaminPaap** [comment]
Triggering a clean for a specific zone is already implemented. Just use the provided service "Zone cleaning service" and put in a comma separated list of rooms in the zone field. The names of the zones should be exactly the same as the names in your MyNeato app.
