### ISSUE TITLE
Initialization Issues - D8

### ISSUE THREAD

**Issue by kbromer** [BenjaminPaap/home-assistant-myneato#6]
v0.0.5
Neato D8 Vacuum 

Having some issues that appear to be related to retrieval of floorplans.  

The vacuum is responsive to commands on a reboot or re-initialization of the integration. I'm able to call the service direct from HA. However, once the vacuum completes one command and returns to the dock, it appears to somehow lose the original floorplan (or that's my guess), resulting in this error on any call utilizing the myneato.custom_cleaning service: 

```
File "/config/custom_components/myneato/vacuum.py", line 397, in myneato_custom_cleaning
    floorplan = self._floorplans.pop()
IndexError: pop from empty list
```

If I attempt to run a full clean with the simple start service it throws a slightly different, but seemingly related, error: 

```
  File "/config/custom_components/myneato/vacuum.py", line 326, in start
    self.robot.start_cleaning(self._floorplans[0])
IndexError: list index out of range
```

Really appreciate the work on this, happy to work with any suggestions or provide whatever additional information is useful.   -TIA

**Comment by BenjaminPaap** [comment]
Hey @kbromer, I just published a new release which addresses your problem. Thanks for the report.

**Comment by kbromer** [comment]
Grateful man, thank you
