### ISSUE TITLE
Floorplans

### ISSUE THREAD

**Issue by martijnrenkema** [BenjaminPaap/home-assistant-myneato#7]
Hi, 

Thanks for this great integration!
I own a D8 and after a year owning it I finally saw this repository.

Installation and login into myneato went flawlessly
Controlling the vacuum is also without without problems.

But is there a way seeing the floorplan in home assistant? 

Thanks!

**Comment by BenjaminPaap** [comment]
Thanks for the feedback. Unfortunately currently there is no way to display a floorplan. I think we got the data, but I wasn't able to extract an image from it yet. If you could help with this I would appreciate a pull request.

**Comment by Bomberski** [comment]
Would this help?

https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card

**Comment by BenjaminPaap** [comment]
Unfortunately not. In the old app the images were given as a url to load the image from. In the new app the raw image data is supplied in the api response.

**Comment by Bomberski** [comment]
> Unfortunately not. In the old app the images were given as a url to load the image from. In the new app the raw image data is supplied in the api response.

Dang, well thanks for making this anyways !

**Comment by BenjaminPaap** [comment]
So I just had some time to take a look into this and found out, that the API response really supplies the floorplan images. The API response from `https://orbital.neatocloud.com/robots/{robot_uuid}/cleaningmaps` looks something like this:

```json
[
  {
    "floorplan_uuid": null,
    "processed_thumb_rank_binary": "iVBORw0KGgoAA...AAAABJRU5ErkJggg==",
    "processed_thumb_real_binary": "iVBORw0KGgo...XHNAAAAAElFTkSuQmCC",
    "processed_thumb_tof_binary": "iVBORw0KGgoAAAAN...ABJRU5ErkJggg==",
    "promotable": false,
    "rank_uuid": "...",
    "runs": [...],
    ...
  }
]
```

`processed_thumb_rank_binary`, `processed_thumb_real_binary`, `processed_thumb_tof_binary` includes a `base64` encoded `png` file which is rotated in my case. So if someone is able to put this in some python code I would be happy to accept a PR for this issue.

**Comment by huubvh95** [comment]
Is anybody already working on this? Otherwise, I will give it a try.

**Comment by BenjaminPaap** [comment]
> Is anybody already working on this? Otherwise, I will give it a try.

I personally got no time currently. So feel free. I would love to see a PR.

**Comment by martijnrenkema** [comment]
> Is anybody already working on this? Otherwise, I will give it a try.

Any updates on this?

**Comment by huubvh95** [comment]
I will try to work on it this weekend. Getting the image from the API was not that hard, but finding out where to put it in HA is more difficult. I am new to writing plugins/code for HA.

**Comment by MustacheNL** [comment]
Hi, since I own a D8 too, any updates on this repo? Would like to see it happen!

**Comment by martijnrenkema** [comment]
> Hi, since I own a D8 too, any updates on this repo? Would like to see it happen!

me too!

**Comment by huubvh95** [comment]
Not much has changed since the last update. I am limited on time and it is a little more complicated than expected. I updated PyNeato to be able to return floorplans [here](https://github.com/huubvh95/pyneato).

**Comment by huubvh95** [comment]
@martijnrenkema @MustacheNL 

Update: I have a working version. I still have some cleanup to do, but that should be finished soon.

**Comment by BenjaminPaap** [comment]
@huubvh95 would love to see a PR for this one.

**Comment by martijnrenkema** [comment]
> @huubvh95 would love to see a PR for this one.

Love to see it!

**Comment by mitch65** [comment]
> @martijnrenkema @MustacheNL
> 
> Update: I have a working version. I still have some cleanup to do, but that should be finished soon.

that's awesome. any pull requests ? 👍

**Comment by huubvh95** [comment]
@mitch65 I was waiting on a new release of pyneato, which has just been created. As soon as I have time I will test with that version and create a MR. This should be possible within the coming two weeks.

**Comment by huubvh95** [comment]
This issue can probably be closed now
