### ISSUE TITLE
No controls from within Home Assistant

### ISSUE THREAD

**Issue by jcovercash** [BenjaminPaap/home-assistant-myneato#8]
I was able to add my vacuums without issue to home assistant using this integration, I added cards to my desktop and can see the status/battery life information. However when I try to run any commands I receive an error "Failed to Call Service Vacuum/Start. List index is out of range. Pressing the locate button works and makes the vacuum ping itself so I can find it But start does not work.

I have ran the vacuum in the neato phone app and that works without issue.

I do have two vacuums added to home assistant using two different neato accounts since their app only allows one vacuum per account. My models are D8 and D10.

Thanks

![image](https://user-images.githubusercontent.com/30985748/218572104-bb025641-1e10-4e15-966f-318c4679d85b.png)

**Comment by BenjaminPaap** [comment]
Hey @jcovercash, did it yet started working like some users reported earlier? If not: Do you have any more infos like log messages with errors originating from this integration?

**Comment by jcovercash** [comment]
Yes It works now I have another issue will make a new case for it.
